### ISSUE TITLE
Execution Of Java Codes in Sandbox

### ISSUE THREAD

**Issue by Nageshmal** [hit-moodle/moodle-local_onlinejudge#62]
I am not able to get any information on how to run Java codes locally in Sandbox.Or rather how to build a sandbox which runs Java programs.I am desperate to work on this.
Please provide me with necessary Hints !!!

**Comment by andrewnaguib** [comment]
[libsandbox](https://github.com/openjudge/sandbox)(which we use to judge programs locally) only supports C, C++, and Python. However, you can always use Sphere Engine to judge [several languages](https://sphere-engine.com/supported-languages).
