### ISSUE TITLE
The course you passed to $PAGE->set_cm does not correspond to the $cm. 

### ISSUE THREAD

**Issue by weng765** [hit-moodle/moodle-local_onlinejudge#65]
Hi,I need help. MY MOODLE is 2.2.1.When Click for more detailed information, It shows that these errors.
Stack trace:
line 815 of /lib/pagelib.php: coding_exception thrown
line 3411 of /lib/navigationlib.php: call to moodle_page->set_cm()
line 2888 of /lib/navigationlib.php: call to settings_navigation->load_module_settings()
line 601 of /lib/pagelib.php: call to settings_navigation->initialise()
line 617 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()
line 2657 of /lib/navigationlib.php: call to moodle_page->__get()
line 659 of /lib/pagelib.php: call to navbar->has_items()
line 4 of /theme/boxxie/layout/general.php: call to moodle_page->has_navbar()
line 685 of /lib/outputrenderers.php: call to include()
line 637 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line ? of unknownfile: call to core_renderer->header()
line 1363 of /lib/setuplib.php: call to call_user_func_array()
line ? of unknownfile: call to bootstrap_renderer->__call()
line 61 of /local/onlinejudge/details.php: call to bootstrap_renderer->header()

**Comment by cmuhirwa** [comment]
Me too I would like to know how to fix it without changing the theme

**Comment by ndrwnaguib** [comment]
hello @cmuhirwa; i'll look into it, can you take some screenshots or tell me the steps to reproduce it, the plugin has been almost rewritten since then, also which version of moodle are you using?
