### ISSUE TITLE
SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by bmkmanoj** [hit-moodle/moodle-local_onlinejudge#71]
I could successfully set up the plugin by following the steps mentioned however, while creating a new assignment I am getting the below mentioned error - I used moodle version '2.4.3+ (Build: 20130502)' 

Exception - SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://ideone.com/api/1/service.wsdl' : failed to load external entity "http://ideone.com/api/1/service.wsdl"

**Comment by Jasintar** [comment]
I have that problem too. Still problem

**Comment by andrewnaguib** [comment]
I will close this issue since we no longer interact with ideone but Sphere Engine instead using REST.
