### ISSUE TITLE
Run $make Error

### ISSUE THREAD

**Issue by Shipu** [hit-moodle/moodle-local_onlinejudge#74]
shipu@psycho /opt/lampp/htdocs/oj/sandbox $ make
make -C libsandbox libsandbox.a
make[1]: Entering directory `/opt/lampp/htdocs/oj/sandbox/libsandbox'
make[1]:`libsandbox.a' is up to date.
make[1]: Leaving directory `/opt/lampp/htdocs/oj/sandbox/libsandbox'
./runtest.sh 1 stdin_test < /dev/null
./runtest.sh 1 stdout_test > /dev/null
./runtest.sh 2 fork_test
./runtest.sh 2 open_test
./runtest.sh 3 -l memory=1048576 memlimit_test
make: **\* [memlimit] Error 1

**Comment by andrewnagyeb** [comment]
Do you remember how did you fix it?

**Comment by chenghuasheng** [comment]
me too!  please help me!

**Comment by andrewnaguib** [comment]
@chenghuasheng Can you try changing the `memlimit` in the following [line](https://github.com/hit-moodle/moodle-local_onlinejudge/blob/214a441111ce91daec202f121f340a404030165c/judge/sandbox/sand/Makefile#L94) to `524288`?
