### ISSUE TITLE
How can I define the testcases?

### ISSUE THREAD

**Issue by calavera2013** [hit-moodle/moodle-local_onlinejudge#76]
Hi,

As teacher, I've created the task (online judge) on moodle correctly. I've defined some parameters such as maximum source file size, programming language, maximum cpy time, ideone username... but  I've the doubt about how I can create the testcases for the task.

Anyone can help me?

Thank you very much!!

**Comment by andrewnaguib** [comment]
If you're still struggling with this issue, would you please provide your Moodle version (i.e., 2 or 3)?
