### ISSUE TITLE
moodle2.9版本可以使用这个插件吗

### ISSUE THREAD

**Issue by qcyclone** [hit-moodle/moodle-local_onlinejudge#81]
RT

**Comment by sunner** [comment]
坦率说，真不知道。已经三年多没维护了。如果你有兴趣，可以搞搞看

**Comment by chenyunfang** [comment]
2.6以下版本才可以用，孙老师。

因为moodle的作业模块 进行了较大调整




chenyunfang999

发件人： Sun Zhigang
发送时间： 2016-01-26 08:53
收件人： hit-moodle/moodle-local_onlinejudge
主题： Re: [moodle-local_onlinejudge] moodle2.9版本可以使用这个插件吗 (#81)
坦率说，真不知道。已经三年多没维护了。如果你有兴趣，可以搞搞看
