### ISSUE TITLE
Guide for Sphere Engine integration

### ISSUE THREAD

**Issue by robert-lewon** [hit-moodle/moodle-local_onlinejudge#86]
Please consider adding a documentation entry about integration with Sphere Engine (i.e. where to register and how to obtain access data).

**Comment by andrewnaguib** [comment]
I have just added it to the [_FAQ_](https://github.com/hit-moodle/moodle-local_onlinejudge/wiki/FAQ#how-to-obtain-sphere-engine-credentials). Please confirm if it's convenient enough.

**Comment by robert-lewon** [comment]
Thank you, now it seems to be very clear!
