### ISSUE TITLE
sandbox does not compile

### ISSUE THREAD

**Issue by iv-enovation** [hit-moodle/moodle-local_onlinejudge#87]
after the plugin ins installed the way it's described in README.md, when running  "cd MOODLE_PATH/local/onlinejudge/judge/sandbox/sand/ && make" compilation fails with:

`cc -m32 -Wall -ansi -std=gnu99 -g0 -O3 -D SANDBOX -D NDEBUG -D WITH_NATIVE_TRACER -D WITHOUT_TSC_COUNTER -I ./libsandbox/src  -o detector sand.o policy_print.o ./libsandbox/libsandbox.a
/usr/bin/ld: sand.o: in function '.L32':
sand.c:(.text.startup+0x57e): undefined reference to 's_result_name'
/usr/bin/ld: sand.c:(.text.startup+0x72d): undefined reference to 's_result_name'
collect2: error: ld returned 1 exit status
make: *** [Makefile:58: detector] Error 1`

This is because inclusion of headers in libsandbox/src/symbols.h are inside #ifndef NDEBUG but -D NDEBUG is set in both Makefile and libsandbox/Makefile

If -D NDEBUG removed from both Makefiles, the compilation still fails at runtest.sh:

`make[1]: Leaving directory '/var/www/ticket/moodle35-1/local/onlinejudge/judge/sandbox/sand/libsandbox'
./runtest.sh 1 stdin_test < /dev/null
debug>entering: sandbox_init(0xffb431c8,0xffb94408)
debug>entering: __sandbox_task_init(0xffb43218)
debug>leaving: __sandbox_task_init()
debug>entering: __sandbox_stat_init(0xffb9423c)
debug>leaving: __sandbox_stat_init()
debug>entering: __sandbox_ctrl_init(0xffb942b4,(nil),(nil))
debug>leaving: __sandbox_ctrl_init()
debug>leaving: sandbox_init()
debug>entering: sandbox_check(0xffb431c8)
debug>passed sandbox status check
debug>entering: __sandbox_task_check(0xffb43218)
debug>passed target program permission test
debug>passed user identity test
debug>passed group identity test
debug>passed set{uid,gid} privilege test
debug>passed jail validity test
debug>passed input channel validity test
debug>leaving: __sandbox_task_check()
debug>leaving: sandbox_check()
make: *** [Makefile:71: stdin] Error 255`

and it looks like the test is completed successfully but the return status is always 255 instead of expected 1

**Comment by andrewnaguib** [comment]
Please give more details on the system environment.

**Comment by iv-enovation** [comment]
sorry, what details? and also, what for? the error is not environment specific, it is clearly a problem of code, as already described

**Comment by andrewnaguib** [comment]
I want to have a full view of the problem. I'm investigating the central reason since it works on several Linux distributions, that's why I am asking.

**Comment by iv-enovation** [comment]
Ok, It's Debian GNU/Linux buster/sid, gcc (Debian 8.2.0-7) 8.2.0, PHP 7.2.9-1 (cli) (built: Aug 19 2018 06:56:13) ( NTS ), GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu), libc6-dev-i386 2.27-6

**Comment by andrewnaguib** [comment]
Hello @iv-enovation, sandbox was upgraded to a new version. Can you try compiling it again following the [instructions](https://github.com/hit-moodle/moodle-local_onlinejudge#sandbox).

**Comment by andrewnaguib** [comment]
This was fixed in andrewnaguib@2c786b4052deea38827d4d3e1b2c82a6627dba3f

**Comment by andrewnaguib** [comment]
This was fixed in andrewnaguib@2c786b4052deea38827d4d3e1b2c82a6627dba3f
