### ISSUE TITLE
$onlinejudge is no-object in mod/assign/feedback/onlinejudge/locallib.php

### ISSUE THREAD

**Issue by iv-enovation** [hit-moodle/moodle-local_onlinejudge#88]
after a fresh installation when entering an assignment configuration page to select the assignment type, multiple notices are shown (in debug mode) saying that:

Notice: Trying to get property of non-object in /var/www/ticket/moodle35-1/mod/assign/feedback/onlinejudge/locallib.php on line 95
Notice: Trying to get property of non-object in /var/www/ticket/moodle35-1/mod/assign/feedback/onlinejudge/locallib.php on line 104
Notice: Trying to get property of non-object in /var/www/ticket/moodle35-1/mod/assign/feedback/onlinejudge/locallib.php on line 113
Notice: Trying to get property of non-object in /var/www/ticket/moodle35-1/mod/assign/feedback/onlinejudge/locallib.php on line 120
Notice: Trying to get property of non-object in /var/www/ticket/moodle35-1/mod/assign/feedback/onlinejudge/locallib.php on line 126
Notice: Trying to get property of non-object in /var/www/ticket/moodle35-1/mod/assign/feedback/onlinejudge/locallib.php on line 135
Notice: Trying to get property of non-object in /var/www/ticket/moodle35-1/mod/assign/feedback/onlinejudge/locallib.php on line 140
Notice: Trying to get property of non-object in /var/www/ticket/moodle35-1/mod/assign/feedback/onlinejudge/locallib.php on line 146
Notice: Trying to get property of non-object in /var/www/ticket/moodle35-1/mod/assign/feedback/onlinejudge/locallib.php on line 152
Notice: Trying to get property of non-object in /var/www/ticket/moodle35-1/mod/assign/feedback/onlinejudge/locallib.php on line 158

**Comment by andrewnaguib** [comment]
Could you please post the steps to reproduce the resulting error?

**Comment by andrewnaguib** [comment]
That behavior was due to using `isset()` on the `$onlinejudge` variable which considers a null variable to be set. However, it is now fixed with using `!empty`.
