### ISSUE TITLE
Error when compling C files through sandbox

### ISSUE THREAD

**Issue by LIU3379** [hit-moodle/moodle-local_onlinejudge#90]
Online Judge 	
Status              [[status-1]]
Judge time 	Sunday, 12 May 2019, 9:43 AM (Assignment was submitted 8 mins 32 secs early)
Source code 	
Details 	        Case 1: [[status-1]]
Success rate 	0
Statistics

what should I do??
Thanks  a lot

**Comment by LIU3379** [comment]
Why is Status not accepted or wrong?

**Comment by andrewnaguib** [comment]
You were able to compile the sandbox successfully?

**Comment by LIU3379** [comment]
yes, cd MOODLE_PATH/local/onlinejudge/judge/sandbox/sand/ && make
，Its output is All testcases are OK。

**Comment by andrewnaguib** [comment]
You've started the judge daemon?

**Comment by LIU3379** [comment]
yes,I have stared the judge daemon and
used: ps-FC PHP to ensure that the daemon is running

**Comment by andrewnaguib** [comment]
If you had started it in the verbose mode using the `-v` argument. Would you please attach its output when judging?

**Comment by LIU3379** [comment]
[root@localhost liubaolong]# sudo -u liubaolong php /var/www/html/moodle/local/onlinejudge/cli/judged.php
Judge daemon successfully created. PID = 2703
[root@localhost liubaolong]# ps -FC php
UID         PID   PPID  C    SZ   RSS PSR STIME TTY          TIME CMD
liubaol+   2703   1753  0 128009 23152  0 09:18 ?        00:00:00 php /var/www/h
[root@localhost liubaolong]# cd /var/www/html/moodle/local/onlinejudge/judge/sandbox/sand/ && make
All testcases are OK
make -C libsandbox clean
make[1]: 进入目录“/var/www/html/moodle/local/onlinejudge/judge/sandbox/sand/libsandbox”
rm -rf doc
rm -f src/platform.o src/sandbox.o src/symbols.o libsandbox.a libsandbox.so \
libsandbox.so.0.2.18
make[1]: 离开目录“/var/www/html/moodle/local/onlinejudge/judge/sandbox/sand/libsandbox”
rm -f *.o *_test detector 223 policy.c

**Comment by LIU3379** [comment]
Is the problem related to the state of SELinux？please，my SELinux state is disabled

**Comment by LIU3379** [comment]
Online Judge
Status [[status-1]]
Judge time Sunday, 12 May 2019, 9:43 AM (Assignment was submitted 8 mins 32 secs early)
Source code
Details Case 1: [[status-1]]

Source code error reporting：error-call to a member function get_filename() on null
what should I do??
Thanks a lot

**Comment by andrewnaguib** [comment]
@LIU3379 What have we reached so far?
