### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Nazikun** [hit-moodle/moodle-local_onlinejudge#91]
PHP pcntl and posix extension must be installed!
我已经安装了 pcntl 和 posix拓展，但出现这个错误

**Comment by menghuanpy** [comment]
是啊。
# sudo -u www-data php onlinejudge/cli/judged.php
PHP pcntl and posix extension must be installed!

出现这个问题，查了一下：
# php -i |grep pcn
pcntl
pcntl support => enabled
为什么报错呢？

**Comment by menghuanpy** [comment]
93    if (!function_exists('**pcntl_fork**') || !function_exists('**posix_setsid**')) {
94        cli_error('PHP pcntl and posix extension must be installed!');
95    }
按照这个修改了，好像就过了，原来的判断有问题哦。
