### ISSUE TITLE
review issues

### ISSUE THREAD

**Issue by iv-enovation** [hit-moodle/moodle-local_onlinejudge#96]
1) During installation -> saving default configuration values
It is not possible to change values for:
- Maximum CPU usage assignment_oj_max_cpu -> "seconds"
- Maximum memory usage assignment_oj_max_mem -> "0 bytes"

2) Sandbox:
- when running make, the compiler is trying to create 32bit executable. This requires an additional OS package to be installed: "gcc-multilib". It is not explained in documentation
- documentation on github outdated re sandbox complilation. In README inside /local/onlinejudge/judge/sandbox/sand only `make` is required
- runtest.sh always fail, $? from "sand" is always not as expected

3) activity backup:
- activity backup is not implemented. An attempt to duplicate and activity in a course fails with an error

4) warnings:
- Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /mod/assign/feedback/onlinejudge/locallib.php on line 435
- ++ Exception encountered in event observer 'onlinejudge_task_judged': Coding error detected, it must be fixed by a programmer: Context level must be CONTEXT_MODULE. ++

5) Not able to use the Sphere engine:
- after editing an existing assignment, entered the Sphere client id/tocken - got the error:
Fatal error: require_once(): Failed opening required '/local/onlinejudge/judge/sphere_engine/api/vendor/autoload.php' (include_path='/lib/pear:.:/usr/share/php') in /mod/assign/feedback/onlinejudge/locallib.php on line 215

**Comment by ndrwnaguib** [comment]
@iv-enovation  

    1. The instructions in the readme weren't accurate. If you installed both plugins at the same time, you would face that issue. However, starting by installing the local plugin and configuring it should fix this issue when installing the feedback plugin (i.e., using the `./install_feedback_assign` script)

   2. I've compiled and upgraded libsandbox, which version were you using? Could you please post the errors?
   3. This has been fixed in https://github.com/hit-moodle/moodle-local_onlinejudge/commit/6a51049d4cf5557ef544a83ea497607d1eead475
   4 & 5. These issues have been fixed in 772aee2c6de3286137ef98720c82376ea1421c21 and 4299cc1f75210073faf3f06d347464f99f55d61a, respectively.
