### ISSUE TITLE
Core Dumped During Sandbox Compilation[!]

### ISSUE THREAD

**Issue by changchencjx** [hit-moodle/moodle-local_onlinejudge#97]
**Describe the bug
Segmentation Fault ( Core Dumped)
make: *** [Makefile: 83: fork] Error 139

**To Reproduce**
1. Run make
2. After executing ./runtest.sh 2 fork_test, the error occurred

**Screenshots**

![QQ图片20210128183801](https://user-images.githubusercontent.com/61176443/106126146-fb5c0580-6197-11eb-9bf7-eea43290ce30.png)

**Moodle:**
 - Version [3.9]
 - It's running under the environment of docker

**Comment by andrewnaguib** [comment]
Does the problem persists on the host machine?

**Comment by changchencjx** [comment]
> Does the problem persists on the host machine?

yes, it still exists
