### ISSUE TITLE
A Question About Its Usage

### ISSUE THREAD

**Issue by changchencjx** [hit-moodle/moodle-local_onlinejudge#98]
Hello, while using onlinejudge by sandbox on moodle, I met a question. First, I logged in as admin and added an assignment, and I set its Testcases like this:

Grade 100%
input: 11
output: 11

Then I uploaded the C File as student:
#include <stdio.h>

int main()
{
      int a;
      scanf("%d",a);
      printf("%d",a);
      return 0;
}

Finally, I logged in as admin again and found that it kept 'judging' instead of giving a score. I think that I may misunderstand its usage or something? @andrewnaguib

**Comment by andrewnaguib** [comment]
Hello @changchencjx! Thank you for submitting your inquiry. 

Are you sure you have the judge daemon running as illustrated in [README#Installation or Uprading](https://github.com/hit-moodle/moodle-local_onlinejudge#installation-upgrading):

For Linux:

```
 In shell, sudo -u www-data php MOODLE_PATH/local/onlinejudge/cli/judged.php, to launch the Judge Daemon.
```

For Windows:

```
php.exe MOODLE_PATH\local\onlinejudge\cli\judged.php -v
```

**Comment by changchencjx** [comment]
> Hello @changchencjx! Thank you for submitting your inquiry.
> 
> Are you sure you have the judge daemon running as illustrated in [README#Installation or Uprading](https://github.com/hit-moodle/moodle-local_onlinejudge#installation-upgrading):
> 
> For Linux:
> 
> ```
>  In shell, sudo -u www-data php MOODLE_PATH/local/onlinejudge/cli/judged.php, to launch the Judge Daemon.
> ```
> 
> For Windows:
> 
> ```
> php.exe MOODLE_PATH\local\onlinejudge\cli\judged.php -v
> ```

Yes, I've already run the daemon. I don't know if the 'input' in Testcases can be used as the value of 'scanf' in C File? @andrewnaguib

**Comment by andrewnaguib** [comment]
Yes, you can! 

Can you please execute the judge daemon with the verbose option by adding `-v` to the arguments, and post the output it shows when it judges your submission?

**Comment by changchencjx** [comment]
> Yes, you can!
> 
> Can you please execute the judge daemon with the verbose option and no daemon by adding to the arguments, and post the output it shows when it judges your submission?`-n -v`

Alright, I checked the shell and found that there was a 'segment fault' during its judgment, I thought there must be something wrong in my environment, and thanks for your help anyway!

**Comment by ndrwnaguib** [comment]
You're welcome!
